Fabio
Rufus97/IRPG-Game pull request #21
Opened 2024-02-16 14:00 UTC by fubu901

2024-02-21 13:52 UTC, Rufus97 requested changes
Fai un pull e poi pusha le tue modifiche

2024-02-22 11:02 UTC, Rufus97 approved these changes

2024-02-22 11:03 UTC, Rufus97 requested changes
Dovresti sistemare la struttura delle cartelle

2024-02-22 11:50 UTC, Rufus97 approved these changes

2024-02-22 17:04 UTC, Rufus97 requested changes
Sistema i metodi di personaggio

2024-02-29 18:10 UTC, fubu901 commented
ciaociao

2024-02-29 18:10 UTC, Rufus97 approved these changes

2024-02-29 18:11 UTC, merged